apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaou
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kaou
  template:
    metadata:
      labels:
        app: kaou
    spec:
      containers:
      - image: okteto.dev/kaou:latest
        name: kaou
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "5e8d3e70-5133-4e25-bfeb-e6793e4ca8fc"
        - name: Vless_Path
          value: "/vl35df5ty"
        - name: Vmess_UUID
          value: "5e8d3e70-5133-4e25-bfeb-e6793e4ca8fc"
        - name: Vmess_Path
          value: "/vmswd6g6"
        - name: Share_Path
          value: "/v2link"
